# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-10"

[[extensions]]
type = "ui_extension"
name = "Parcelamento POS"

handle = "installments-pos"
description = "Este app é uma extensão do Shopify para lojas brasileiras que processam pagamentos externamente, como em máquinas de cartão. Ele permite que os lojistas registrem a quantidade de parcelas escolhidas pelo cliente e armazenem essa informação no checkout, facilitando o gerenciamento financeiro e integrando de forma eficiente com sistemas ERP."

# Controls where in POS your extension will be injected,
# and the file that contains your extension’s source code.
[[extensions.targeting]]
module = "./src/Tile.jsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.jsx"
target = "pos.home.modal.render"

[[extensions.targeting]]
module = "./src/PostPurchaseAction.jsx"
target = "pos.purchase.post.action.menu-item.render"

[[extensions.targeting]]
module = "./src/PostPurchaseActionModal.jsx"
target = "pos.purchase.post.action.render"

[[extensions.targeting]]
module = "./src/OrderDetails.jsx"
target = "pos.order-details.block.render"
